### PR TITLE
Use react-native-blob-util ^0.13.7

### LINKED ISSUE #55: Update rn-fetch-blob dependency.
rn-fetch-blob was deprecated/unmaintained once again (https://github.com/joltup/rn-fetch-blob/issues/666)

The new home for this library (new fork) is at https://github.com/RonRadtke/react-native-blob-util

Would you consider either removing the hard dependency to rn-fetch-blob so either can be used, or just migrating to the new dependency? Otherwise, users using this library will be forever stuck with the deprecated one.

Thanks.

### PR DESCRIPTION
**Pull request by robwalkerco**
Switch to using [react-native-blob-util](https://github.com/RonRadtke/react-native-blob-util) 

Closes #55

### CODE REVIEW

**Comment by robwalkerco** [comment]
@imranMnts I've setup the change in this PR.

I'd really appreciate if you are able to confirm that everything is good for me, by installing this branch and testing it your quickly in your app. (I'm not actually actively using this project right now)

You can install it by simply swapping the npm version in your package.json file with `git+https://github.com/robwalkerco/redux-persist-filesystem-storage.git#813045c3ee14199a5a503e15c2148a40ba66998c`, then running `yarn` or `npm` to update the dependancies.

**Comment by imranMnts** [comment]
@robwalkerco 

It doesn't work, looks like you still use `rn-fetch-blob` in the code.

https://github.com/robwalkerco/redux-persist-filesystem-storage/blob/813045c3ee14199a5a503e15c2148a40ba66998c/index.js#L5

we have to use `import ReactNativeBlobUtil from 'react-native-blob-util'` with the new one.

**Comment by robwalkerco** [comment]
@imranMnts I've corrected the import.

It would be great if you could give it another try 🙏

**Comment by imranMnts** [comment]
I encountered this issue..
https://github.com/RonRadtke/react-native-blob-util/issues/33

**Comment by williamgurzoni** [comment]
Hi, will it be merged?

**Comment by midhunm-c** [comment]
Hi, we are migrating to `RonRadtke/react-native-blob-util` from `rn-fetch-blob`, so can we expect this to be merged soon?
It would be very helpful if migrated to `react-native-blob-util`.
Thank you !!

**Comment by midhunm-c** [comment]
Hi, we have changed our app dependancy to `RonRadtke/react-native-blob-util`, so can we expect this to be merged soon?
It would be very helpful if dependancy changed to `react-native-blob-util`.
Thank you !!

**Comment by robwalkerco** [comment]
I'd really appreciate if a few users would be able to confirm that everything is good with this PR, by installing this branch and testing it your quickly in your app. (I'm not actually actively using this project right now).
I would then be more confident to release this as version 4.0.0 on npm

You can install it by simply swapping the npm version in your package.json file with git+https://github.com/robwalkerco/redux-persist-filesystem-storage.git#22514a2ee00482ff3827a5da8f1722badbaac6d0, then running yarn or npm to update the dependencies.

**Pull request closed without merging**
